version: '3.1'
services:
  book_mong:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: book
    ports:
    - 27018:27017
    volumes:
      - ./BookOfAdventure/src/main/docker/mongo/:/docker-entrypoint-initdb.d/:ro
  dungeon_mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./Dungeon/src/main/docker/mongo/:/docker-entrypoint-initdb.d/:ro
  mongo-express:
    image: mongo-express
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
    depends_on:
      - dungeon_mongo
